<?php

namespace App;
use App\SurveyUnitUsaha;
use App\PengawasKesmavet;
use App\UnitUsaha;

use Illuminate\Database\Eloquent\Model;

class Form3 extends Model
{
    public $timestamps = false;
    
    protected $table = 'form3';
    
    protected $fillable = [
        'kapasitasPemeliharaan', 
        'jumlahPopulasi', 
        'skalaUsaha', 
        'produksiTelurPerHari', 
        'produksiTelurPerBulan', 
        'kapasitasGudangTelur', 
        'realisasiPemanfaatan', 
        'check_wilayahPeredaran_1', 
        'wilayahPeredaran_1', 
        'check_wilayahPeredaran_2', 
        'wilayahPeredaran_2', 
        'check_wilayahPeredaran_3', 
        'wilayahPeredaran_3',
        'check_wilayahPeredaran_4', 
        'wilayahPeredaran_4', 
        'jumlahSDM', 
        'check_p1_1',
        'P1_1_1',
        'P1_1_2', 
        'check_p1_2',
        'P1_2_1',
        'P1_2_2',
        'check_p1_3',
        'P1_3_1',
        'P1_3_2', 
        'check_p1_4',
        'P1_4_1',
        'P1_4_2', 
        'check_p2',
        'P2_1',
        'P2_2', 
        'P2_3', 
        'P2_4',
        'P2_5',
        'P2_6',
        'check_p3',
        'P3_1',
        'P3_2', 
        'P3_3', 
        'P3_4', 
        'check_p4', 
        'P4_1', 
        'P4_2', 
        'P4_3', 
        'P4_4', 
        'P4_5', 
        'check_p5', 
        'P5_1', 
        'P5_2', 
        'P5_3', 
        'P5_4', 
        'P5_5', 
        'P5_6', 
        'P5_7', 
        'check_p6',
        'P6_1', 
        'P6_2', 
        'check_p7', 
        'P7_1', 
        'P7_2', 
        'P7_3', 
        'check_p8', 
        'P8_1', 
        'P8_2', 
        'P8_3', 
        'P8_4', 
        'check_p9', 
        'P9_1', 
        'P9_2', 
        'check_p10', 
        'P10_1', 
        'P10_2', 
        'P10_3', 
        'check_p11', 
        'P11_1', 
        'P11_2', 
        'check_p12', 
        'P12_1', 
        'P12_2', 
        'P12_3', 
        'check_p13', 
        'P13_1', 
        'P13_2', 
        'check_p14', 
        'P14_1', 
        'P14_2', 
        'P14_3', 
        'P14_4', 
        'check_p15', 
        'P15_1', 
        'P15_2', 
        'P15_3', 
        'P15_4', 
        'P15_5', 
        'P15_6', 
        'check_p16',
        'P16', 
        'check_p17', 
        'P17_1', 
        'P17_2', 
        'P17_3', 
        'check_p18', 
        'P18_1', 
        'P18_2', 
        'P18_3', 
        'P18_4', 
        'P18_5', 
        'check_p19', 
        'P19_1', 
        'P19_2', 
        'P19_3', 
        'P19_4', 
        'check_p20', 
        'P20_1', 
        'P20_2', 
        'P20_3', 
        'P20_4', 
        'P20_5', 
        'P20_6', 
        'P20_7',
        'check_p21', 
        'P21_1', 
        'P21_2', 
        'check_p22',
        'P22_1', 
        'P22_2', 
        'P22_3', 
	];

	public function surveyUnitUsaha()
	{
		return $this->belongsTo('App\SurveyUnitUsaha', 'id', 'idForm3');
	}
}
