<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class form6 extends Model
{
    protected $table = 'form6';

    public $timestamps = false;

    protected $fillable = [
      'tipeUnitUsaha',
      'jenisProduk',
      'karyawanProduksi_L',
      'karyawanProduksi_P',
      'karyawanAdm_L',
      'karyawanAdm_P',
      'karyawanAMPM',
      'karyawanAWO',
      'juruSembelih',
      'operatorStunning',
      "b1_niu_id" ,
      "b1_niu_date",
      "b1_npwp_id" ,
      "b1_npwp_date" ,
      "b1_siup_id" ,
      "b1_siup_date" ,
      "b1_nib_id" ,
      "b1_nib_date" ,
      "b1_pks_id" ,
      "b1_pks_date" ,
      "check_b2" ,
      "check_b3" ,
      "b3_1" ,
      "b3_2" ,
      "b3_3" ,
      "check_b4" ,
      "b4_id" ,
      "check_b5_1" ,
      "b5_1_nama" ,
      "b5_1_alamat" ,
      "b5_1_sertifikat" ,
      "check_b5_2",
      "b5_2_nama" ,
      "b5_2_alamat" ,
      "b5_2_sertifikat" ,
      "check_b5_3" ,
      "b5_3_nama" ,
      "b5_3_alamat" ,
      "b5_3_sertifikat" ,
      "check_b6" ,
      "b6_1" ,
      "b6_2" ,
      "b6_3" ,
      "b6_4" ,
      "check_b7" ,
      "b7" ,
      "check_b8" ,
      "b8_1" ,
      "b8_2" ,
      "check_b9" ,
      "b9" ,
      "check_b10" ,
      "b10" ,
      "check_b11",
      "b11",
      "check_b12" ,
      "b12" ,
      "check_b13" ,
      "b13" ,
      "check_b14",
      "b14" ,
      "check_b15" ,
      "b15" ,
      "check_b16" ,
      "b16" ,
      "check_b17" ,
      "b17" ,
      "check_b18" ,
      "b18" ,
      "b19" ,
      "b20" ,
      "b21_1" ,
      "b21_2" ,
      "b22" ,
      "b23_1" ,
      "b23_2" ,
      "b24" ,
      "b25_1" ,
      "b25_2" ,
      "b26_1" ,
      "b26_2" ,
      "b27_1" ,
      "b27_2" ,
      "b27_3" ,
      "check_b28" ,
      "b28_1",
      "b28_2" ,
      "b28_3" ,
      "check_b29" ,
      "b29_unit" ,
      "b29_kapasitas" ,
      "b29_realisasi" ,
      "b29_metode" ,
      "check_b30" ,
      "b30_unit" ,
      "b30_kapasitas",
      "b30_realisasi" ,
      "b30_waktu" ,
      "b30_alamat" ,
      "check_b31" ,
      "b31" ,
      "check_b32" ,
      "b32_jenisAlat" ,
      "b32_jumlahAlat" ,
      "b32_kapasitas" ,
      'check_b33',
      "b33" ,
      "b4_file" ,
      ];

}
